name: CI

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    branches:
      - main
      - dev
      - feat/*
      - feature/*

permissions:
  actions: read
  contents: read

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml

  linters:
    name: Linters
    uses: ./.github/workflows/linters.yml

  eslint-review:
    name: ESLint Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
