# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml

  linters:
    name: Linters
    uses: ./.github/workflows/linters.yml

  eslint-review:
    name: ESLint Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
